name: MFLogger
version: 1.1
main: com.mateus.mflogger.MFLoggerPlugin
author: Mateusaum
commands:
  getLogs:
    description: Pega todas as informações logadas em uma região
permissions:
  mflogger.admin:
    description: Permissão para executar o comando de recuperar registros em uma região
  
